services:
  dev:
    volumes:
      - type: bind
        source: /Users/hagevvashi/.bash_history
        target: /home/${UNAME:-vscode}/.bash_history
        consistency: cached
      - type: bind
        source: /Users/hagevvashi/.git
        target: /home/${UNAME:-vscode}/.git
        consistency: cached
      - type: bind
        source: /Users/hagevvashi/.ssh
        target: /home/${UNAME:-vscode}/.ssh
        consistency: cached
      - type: bind
        source: /Users/hagevvashi/.gitconfig
        target: /home/${UNAME:-vscode}/.gitconfig
        consistency: cached
      - type: bind
        source: /Users/hagevvashi/.aws
        target: /home/${UNAME:-vscode}/.aws
        consistency: cached
      - type: bind
        source: /Users/hagevvashi/.claude
        target: /home/${UNAME:-vscode}/.claude
        consistency: cached
      - type: bind
        source: /Users/hagevvashi/.claude.json
        target: /home/${UNAME:-vscode}/.claude.json
        consistency: cached
      - type: bind
        source: /Users/hagevvashi/.config/code-server
        target: /home/${UNAME:-vscode}/.config/code-server
        consistency: cached
      - type: bind
        source: /Users/hagevvashi/.config/gh
        target: /home/${UNAME:-vscode}/.config/gh
        consistency: cached
      - type: bind
        source: /Users/hagevvashi/.config/gcloud
        target: /home/${UNAME:-vscode}/.config/gcloud
        consistency: cached
      - type: bind
        source: /Users/hagevvashi/.config/atuin
        target: /home/${UNAME:-vscode}/.config/atuin
        consistency: cached
      - type: bind
        source: /Users/hagevvashi/.local/share/atuin
        target: /home/${UNAME:-vscode}/.local/share/atuin
        consistency: cached
      - type: bind
        source: /Users/hagevvashi/.cursor
        target: /home/${UNAME:-vscode}/.cursor
        consistency: cached
